package it.unisa.diem.softwareengineering.assignment2021;


import java.awt.event.KeyEvent;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



public class GUI extends javax.swing.JFrame {
    
    
    Manager manager;
    private final static int readlimiter = 12; //.... 
    
    PersonalizedOperationsWindow opPane = new PersonalizedOperationsWindow();
    VariablesWindow varPane = new VariablesWindow();
    JFrame frame = new JFrame();
    JFrame frame2 = new JFrame();
    
     
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        manager = Manager.getManager();
        //manager.observeVariables(varPane);
   
        //Assign to frames the extra-panels
        frame.setTitle("Personalized Operations");
        frame.add(opPane);
        frame2.setTitle("Variables");
        frame2.add(varPane);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        inputTextField = new javax.swing.JTextField();
        computeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        dropButton = new javax.swing.JButton();
        dupButton = new javax.swing.JButton();
        overButton = new javax.swing.JButton();
        swapButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        memoButton = new javax.swing.JButton();
        variablesButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        nFourButton = new java.awt.Button();
        plusButton = new java.awt.Button();
        minusButton = new java.awt.Button();
        divisionButton = new java.awt.Button();
        multiplyButton = new java.awt.Button();
        nOnerButton = new java.awt.Button();
        inverteButton = new java.awt.Button();
        nSevenButton = new java.awt.Button();
        nTwoButton = new java.awt.Button();
        nFiveButton = new java.awt.Button();
        nEightButton = new java.awt.Button();
        nThreeButton = new java.awt.Button();
        nSixButton = new java.awt.Button();
        nNineButton = new java.awt.Button();
        nJButton = new java.awt.Button();
        sqrtButton = new java.awt.Button();
        nZeroButton1 = new java.awt.Button();
        delButton = new java.awt.Button();
        cleareTextButton = new java.awt.Button();
        dotButton2 = new java.awt.Button();
        jSeparator2 = new javax.swing.JSeparator();
        expButton = new java.awt.Button();
        argButton = new java.awt.Button();
        modButton3 = new java.awt.Button();
        powButton1 = new java.awt.Button();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Complex Calculator");

        jPanel1.setBackground(new java.awt.Color(0, 72, 121));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        textArea.setForeground(new java.awt.Color(10, 82, 121));
        textArea.setRows(5);
        textArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(207, 237, 242), new java.awt.Color(207, 237, 242), null, null));
        textArea.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(textArea);

        jPanel2.setBackground(new java.awt.Color(45, 161, 200));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 237, 242), 1, true));

        inputTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputTextField.setForeground(new java.awt.Color(0, 72, 121));
        inputTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        inputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTextFieldKeyPressed(evt);
            }
        });

        computeButton.setBackground(new java.awt.Color(207, 237, 242));
        computeButton.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        computeButton.setForeground(new java.awt.Color(0, 72, 121));
        computeButton.setText("COMPUTE");
        computeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        computeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(computeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTextField)
                    .addComponent(computeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(45, 161, 200));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 237, 242), 1, true));

        clearButton.setBackground(new java.awt.Color(207, 237, 242));
        clearButton.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        clearButton.setForeground(new java.awt.Color(0, 72, 121));
        clearButton.setText("CLEAR");
        clearButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        dropButton.setBackground(new java.awt.Color(207, 237, 242));
        dropButton.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        dropButton.setForeground(new java.awt.Color(0, 72, 121));
        dropButton.setText("DROP");
        dropButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        dupButton.setBackground(new java.awt.Color(207, 237, 242));
        dupButton.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        dupButton.setForeground(new java.awt.Color(0, 72, 121));
        dupButton.setText("DUP");
        dupButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        dupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dupButtonActionPerformed(evt);
            }
        });

        overButton.setBackground(new java.awt.Color(207, 237, 242));
        overButton.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        overButton.setForeground(new java.awt.Color(0, 72, 121));
        overButton.setText("OVER");
        overButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        overButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overButtonActionPerformed(evt);
            }
        });

        swapButton.setBackground(new java.awt.Color(207, 237, 242));
        swapButton.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        swapButton.setForeground(new java.awt.Color(0, 72, 121));
        swapButton.setText("SWAP");
        swapButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        swapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(dropButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(swapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(swapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(55, 200, 180));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        memoButton.setBackground(new java.awt.Color(207, 237, 242));
        memoButton.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        memoButton.setForeground(new java.awt.Color(0, 72, 121));
        memoButton.setText("MEMO");
        memoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        memoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoButtonActionPerformed(evt);
            }
        });

        variablesButton.setBackground(new java.awt.Color(207, 237, 242));
        variablesButton.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        variablesButton.setForeground(new java.awt.Color(0, 72, 121));
        variablesButton.setText("VAR");
        variablesButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        variablesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variablesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(variablesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(variablesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(45, 161, 200));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 237, 242), 1, true));

        nFourButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nFourButton.setForeground(new java.awt.Color(0, 72, 121));
        nFourButton.setLabel("4");
        nFourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nFourButtonActionPerformed(evt);
            }
        });

        plusButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        plusButton.setForeground(new java.awt.Color(0, 72, 121));
        plusButton.setLabel("+");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        minusButton.setForeground(new java.awt.Color(0, 72, 121));
        minusButton.setLabel("-");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        divisionButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        divisionButton.setForeground(new java.awt.Color(0, 72, 121));
        divisionButton.setLabel("/");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        multiplyButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        multiplyButton.setForeground(new java.awt.Color(0, 72, 121));
        multiplyButton.setLabel("*");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        nOnerButton.setBackground(new java.awt.Color(255, 255, 255));
        nOnerButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nOnerButton.setForeground(new java.awt.Color(0, 72, 121));
        nOnerButton.setLabel("1");
        nOnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nOnerButtonActionPerformed(evt);
            }
        });

        inverteButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        inverteButton.setForeground(new java.awt.Color(0, 72, 121));
        inverteButton.setLabel("+ -");
        inverteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inverteButtonActionPerformed(evt);
            }
        });

        nSevenButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nSevenButton.setForeground(new java.awt.Color(0, 72, 121));
        nSevenButton.setLabel("7");
        nSevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nSevenButtonActionPerformed(evt);
            }
        });

        nTwoButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nTwoButton.setForeground(new java.awt.Color(0, 72, 121));
        nTwoButton.setLabel("2");
        nTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nTwoButtonActionPerformed(evt);
            }
        });

        nFiveButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nFiveButton.setForeground(new java.awt.Color(0, 72, 121));
        nFiveButton.setLabel("5");
        nFiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nFiveButtonActionPerformed(evt);
            }
        });

        nEightButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nEightButton.setForeground(new java.awt.Color(0, 72, 121));
        nEightButton.setLabel("8");
        nEightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nEightButtonActionPerformed(evt);
            }
        });

        nThreeButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nThreeButton.setForeground(new java.awt.Color(0, 72, 121));
        nThreeButton.setLabel("3");
        nThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nThreeButtonActionPerformed(evt);
            }
        });

        nSixButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nSixButton.setForeground(new java.awt.Color(0, 72, 121));
        nSixButton.setLabel("6");
        nSixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nSixButtonActionPerformed(evt);
            }
        });

        nNineButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nNineButton.setForeground(new java.awt.Color(0, 72, 121));
        nNineButton.setLabel("9");
        nNineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nNineButtonActionPerformed(evt);
            }
        });

        nJButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nJButton.setForeground(new java.awt.Color(0, 72, 121));
        nJButton.setLabel("j");
        nJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nJButtonActionPerformed(evt);
            }
        });

        sqrtButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        sqrtButton.setForeground(new java.awt.Color(0, 72, 121));
        sqrtButton.setLabel("sqrt");
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });

        nZeroButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nZeroButton1.setForeground(new java.awt.Color(0, 72, 121));
        nZeroButton1.setLabel("0");
        nZeroButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nZeroButton1ActionPerformed(evt);
            }
        });

        delButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        delButton.setForeground(new java.awt.Color(0, 72, 121));
        delButton.setLabel("DEL");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        cleareTextButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cleareTextButton.setForeground(new java.awt.Color(0, 72, 121));
        cleareTextButton.setLabel("C");
        cleareTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleareTextButtonActionPerformed(evt);
            }
        });

        dotButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        dotButton2.setForeground(new java.awt.Color(0, 72, 121));
        dotButton2.setLabel(".");
        dotButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButton2ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(207, 237, 242));
        jSeparator2.setForeground(new java.awt.Color(207, 237, 242));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        expButton.setActionCommand("EXP");
        expButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        expButton.setForeground(new java.awt.Color(0, 72, 121));
        expButton.setLabel("EXP");
        expButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expButtonActionPerformed(evt);
            }
        });

        argButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        argButton.setForeground(new java.awt.Color(0, 72, 121));
        argButton.setLabel("ARG");
        argButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                argButtonActionPerformed(evt);
            }
        });

        modButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        modButton3.setForeground(new java.awt.Color(0, 72, 121));
        modButton3.setLabel("MOD");
        modButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modButton3ActionPerformed(evt);
            }
        });

        powButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        powButton1.setForeground(new java.awt.Color(0, 72, 121));
        powButton1.setLabel("POW");
        powButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(powButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inverteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(argButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(nFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(nOnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cleareTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(dotButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nZeroButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(expButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(nSevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(inverteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(argButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(nThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(nOnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nSixButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nFourButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(nTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(sqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nSevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(powButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nZeroButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cleareTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dotButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(45, 161, 200));
        jSeparator1.setForeground(new java.awt.Color(207, 237, 242));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is called when the button is pressed or when in the inputTextFiled area the "enter" key
     * is pressed, it is used to insert a new number, operator or function in the memory, (take it from the inputTextField) 
     * @param evt 
     */
    private void computeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeButtonActionPerformed

        if(computeButton.isEnabled())
            runTask(inputTextField.getText());
    }
    
//GEN-LAST:event_computeButtonActionPerformed
    /**
     * This method is called when the user press the "enter" key inside the inputTextField.
     * This is the equivalent of clicking on the button "compute" 
     * @param evt 
     */
    private void inputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextFieldKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            computeButton.doClick();
        }
    }//GEN-LAST:event_inputTextFieldKeyPressed

    /**
     * This method clear the memory
     * @param evt 
     */
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        runTask("clear");
    }//GEN-LAST:event_clearButtonActionPerformed
    /**
     * This method drop the last element inserted in the memory
     * @param evt 
     */
    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        runTask("drop");
    }//GEN-LAST:event_dropButtonActionPerformed
    /**
     * This method duplicate the last element inserted in the memory
     * @param evt 
     */
    private void dupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dupButtonActionPerformed
        runTask("dup");
    }//GEN-LAST:event_dupButtonActionPerformed
    /**
     * This method duplicate the penultimate element inserted in the memory
     * @param evt 
     */
    private void overButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overButtonActionPerformed
        runTask("over");
    }//GEN-LAST:event_overButtonActionPerformed
    /**
     * This method swap the last and the penultimate element inserted in the memory
     * @param evt 
     */
    private void swapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swapButtonActionPerformed
        runTask("swap");
    }//GEN-LAST:event_swapButtonActionPerformed

    private void memoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoButtonActionPerformed
        
        frame.setVisible(true);
        frame.pack();
    }//GEN-LAST:event_memoButtonActionPerformed

    private void nFourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nFourButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "4");
    }//GEN-LAST:event_nFourButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "+");
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "-");
    }//GEN-LAST:event_minusButtonActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        inputTextField.setText("/");
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        inputTextField.setText("*");
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void nOnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nOnerButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "1");
    }//GEN-LAST:event_nOnerButtonActionPerformed

    private void inverteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inverteButtonActionPerformed
        inputTextField.setText("+-");
    }//GEN-LAST:event_inverteButtonActionPerformed

    private void nSevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nSevenButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "7");
    }//GEN-LAST:event_nSevenButtonActionPerformed

    private void nTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTwoButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "2");
    }//GEN-LAST:event_nTwoButtonActionPerformed

    private void nFiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nFiveButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "5");
    }//GEN-LAST:event_nFiveButtonActionPerformed

    private void nEightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nEightButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "8");
    }//GEN-LAST:event_nEightButtonActionPerformed

    private void nThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nThreeButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "3");
    }//GEN-LAST:event_nThreeButtonActionPerformed

    private void nSixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nSixButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "6");
    }//GEN-LAST:event_nSixButtonActionPerformed

    private void nNineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nNineButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "9");
    }//GEN-LAST:event_nNineButtonActionPerformed

    private void nJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nJButtonActionPerformed
        inputTextField.setText(inputTextField.getText() + "j");
    }//GEN-LAST:event_nJButtonActionPerformed

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        inputTextField.setText("sqrt");
    }//GEN-LAST:event_sqrtButtonActionPerformed

    private void nZeroButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nZeroButton1ActionPerformed
        inputTextField.setText(inputTextField.getText() + "0");
    }//GEN-LAST:event_nZeroButton1ActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        String str = inputTextField.getText();
        inputTextField.setText(str.substring(0, str.length()-1));
    }//GEN-LAST:event_delButtonActionPerformed

    private void cleareTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleareTextButtonActionPerformed
        inputTextField.setText(null);
    }//GEN-LAST:event_cleareTextButtonActionPerformed

    private void dotButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButton2ActionPerformed
        inputTextField.setText(inputTextField.getText() + ".");
    }//GEN-LAST:event_dotButton2ActionPerformed

    private void variablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variablesButtonActionPerformed

        frame2.setVisible(true);
        frame2.pack();
    }//GEN-LAST:event_variablesButtonActionPerformed

    private void expButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expButtonActionPerformed
        inputTextField.setText("exp");
    }//GEN-LAST:event_expButtonActionPerformed

    private void argButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_argButtonActionPerformed
        inputTextField.setText("arg");
    }//GEN-LAST:event_argButtonActionPerformed

    private void modButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modButton3ActionPerformed
        inputTextField.setText("mod");
    }//GEN-LAST:event_modButton3ActionPerformed

    private void powButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powButton1ActionPerformed
        inputTextField.setText("pow");
    }//GEN-LAST:event_powButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                
            }
        });
    }
    //----------------------------------------------------------------- Private methods ------------------------------------------------------------------
    
    /**
     * This methods check if the input (operators, function, operators) is valid and run the task required or, it will notificate an error through a pop-up notification
     * @param text 
     */
    private void runTask(String text){
        computeButton.setEnabled(false);
        clearButton.setEnabled(false);
        dropButton.setEnabled(false);
        dupButton.setEnabled(false);
        overButton.setEnabled(false);
        swapButton.setEnabled(false);
        
        try{ 
            manager.processInput(text);
            
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "The inserted element is neither a number nor an operation!");
            
        } catch (NotEnoughOperatorsException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            
        } catch (ArithmeticException ex) {
            JOptionPane.showMessageDialog(rootPane, "Arithmetic Error: " + ex.getMessage());
            
        }finally{
            printOnTextArea();
            computeButton.setEnabled(true);
            clearButton.setEnabled(true);
            dropButton.setEnabled(true);
            dupButton.setEnabled(true);
            overButton.setEnabled(true);
            swapButton.setEnabled(true);
        }
    }
    
    /**
     * This method is called whenever a methods needs to update the Output in the textArea (it also clean the inputTextfield). 
     */ 
    private void printOnTextArea(){
        inputTextField.setText(null); //clean the inputTextField
        Iterator<ComplexNumber> memory = manager.getMemory();
        int flag = 0;
        String str = "";
        while (memory.hasNext() && flag < readlimiter){
            ComplexNumber a = memory.next();
            str = a.toString() +"\n" + str;
            flag += 1;
        }
        textArea.setText(str);
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button argButton;
    private javax.swing.JButton clearButton;
    private java.awt.Button cleareTextButton;
    private javax.swing.JButton computeButton;
    private java.awt.Button delButton;
    private java.awt.Button divisionButton;
    private java.awt.Button dotButton2;
    private javax.swing.JButton dropButton;
    private javax.swing.JButton dupButton;
    private java.awt.Button expButton;
    private javax.swing.JTextField inputTextField;
    private java.awt.Button inverteButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton memoButton;
    private java.awt.Button minusButton;
    private java.awt.Button modButton3;
    private java.awt.Button multiplyButton;
    private java.awt.Button nEightButton;
    private java.awt.Button nFiveButton;
    private java.awt.Button nFourButton;
    private java.awt.Button nJButton;
    private java.awt.Button nNineButton;
    private java.awt.Button nOnerButton;
    private java.awt.Button nSevenButton;
    private java.awt.Button nSixButton;
    private java.awt.Button nThreeButton;
    private java.awt.Button nTwoButton;
    private java.awt.Button nZeroButton1;
    private javax.swing.JButton overButton;
    private java.awt.Button plusButton;
    private java.awt.Button powButton1;
    private java.awt.Button sqrtButton;
    private javax.swing.JButton swapButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JButton variablesButton;
    // End of variables declaration//GEN-END:variables
}
