/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unisa.diem.softwareengineering.assignment2021;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre
 */
public class VariablesWindow extends javax.swing.JPanel implements Observer {

   private final DefaultTableModel model;
   private final Manager manager;
   private String selectedVariable = "x";
   
    public VariablesWindow() {
        initComponents();
        manager = Manager.getManager();
        model = (DefaultTableModel)table.getModel();
        buildTable();
        
        //this anonymous class returns the key and the value of the selected row
        table.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent m){
                int row = table.getSelectedRow();
                selectedVariable = table.getModel().getValueAt(row, 0).toString();
                storeInVariableButton.setLabel(">" + selectedVariable);
                loadFromVariableButton.setLabel("<" + selectedVariable);
                sumToVariableButton.setLabel("+" + selectedVariable);
                substractToVariableButton.setLabel("-" + selectedVariable);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        restoreButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        resetOpButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        storeInVariableButton = new javax.swing.JButton();
        loadFromVariableButton = new javax.swing.JButton();
        sumToVariableButton = new javax.swing.JButton();
        substractToVariableButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 72, 121));
        jPanel1.setName("Personalised Operation"); // NOI18N

        table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240)));
        table.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        table.setForeground(new java.awt.Color(0, 72, 121));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VARIABLES ", "CURRENT VALUE", "OLD VALUE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.setOpaque(false);
        table.setRowHeight(28);
        table.setRowMargin(2);
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.setSelectionForeground(new java.awt.Color(128, 0, 128));
        table.setShowGrid(true);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(5);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(50);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jPanel2.setBackground(new java.awt.Color(55, 200, 180));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        saveButton.setBackground(new java.awt.Color(207, 237, 242));
        saveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 72, 121));
        saveButton.setText("SAVE");
        saveButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        restoreButton.setBackground(new java.awt.Color(207, 237, 242));
        restoreButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        restoreButton.setForeground(new java.awt.Color(0, 72, 121));
        restoreButton.setText("RESTORE");
        restoreButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        restoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(207, 237, 242));
        jSeparator1.setForeground(new java.awt.Color(207, 237, 242));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(207, 237, 242), new java.awt.Color(207, 237, 242), new java.awt.Color(207, 237, 242), new java.awt.Color(207, 237, 242)));

        jPanel3.setBackground(new java.awt.Color(55, 200, 180));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        resetOpButton.setBackground(new java.awt.Color(207, 237, 242));
        resetOpButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetOpButton.setForeground(new java.awt.Color(0, 72, 121));
        resetOpButton.setText("RESET");
        resetOpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        resetOpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetOpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resetOpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resetOpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(45, 161, 200));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        storeInVariableButton.setBackground(new java.awt.Color(207, 237, 242));
        storeInVariableButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        storeInVariableButton.setForeground(new java.awt.Color(0, 72, 121));
        storeInVariableButton.setText(">x");
        storeInVariableButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        storeInVariableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeInVariableButtonActionPerformed(evt);
            }
        });

        loadFromVariableButton.setBackground(new java.awt.Color(207, 237, 242));
        loadFromVariableButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loadFromVariableButton.setForeground(new java.awt.Color(0, 72, 121));
        loadFromVariableButton.setText("<x");
        loadFromVariableButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        loadFromVariableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFromVariableButtonActionPerformed(evt);
            }
        });

        sumToVariableButton.setBackground(new java.awt.Color(207, 237, 242));
        sumToVariableButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sumToVariableButton.setForeground(new java.awt.Color(0, 72, 121));
        sumToVariableButton.setText("+x");
        sumToVariableButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        sumToVariableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumToVariableButtonActionPerformed(evt);
            }
        });

        substractToVariableButton.setBackground(new java.awt.Color(207, 237, 242));
        substractToVariableButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        substractToVariableButton.setForeground(new java.awt.Color(0, 72, 121));
        substractToVariableButton.setText("-x");
        substractToVariableButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 72, 121), 0, true));
        substractToVariableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractToVariableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(storeInVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadFromVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumToVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substractToVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storeInVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadFromVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sumToVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(substractToVariableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * This method is used to save the run-time variables, showing a pop-up to ask for confirmation
     * @param evt 
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Object[] options = {"yes","no"};
        int response = JOptionPane.showOptionDialog(table, "Are you sure you want to save?", "Saving", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, "");
        if(response == 0){
            try {
                manager.processInput("save");
            } catch (NumberFormatException | NotEnoughOperatorsException | ArithmeticException ex) {
                JOptionPane.showMessageDialog(table, ex.getMessage());
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    
    /**
     * This method is used to restore the old version of the run-time variables, showing a pop-up to ask for confirmation
     * @param evt 
     */
    private void restoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreButtonActionPerformed
        Object[] options = {"yes","no"};
        int response = JOptionPane.showOptionDialog(table, "Are you sure you want to restore the old values?", "Restoring", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, "");
        if(response == 0){
            try{
                manager.processInput("restore");
            } catch (NumberFormatException | NotEnoughOperatorsException | ArithmeticException | NoSuchElementException ex) {
                JOptionPane.showMessageDialog(table, ex.getMessage());
                }
            
        }
        buildTable();
    }//GEN-LAST:event_restoreButtonActionPerformed
    
    /**
     * This method is used to clear the run-time variables, showing a pop-up to ask for confirmation
     * @param evt 
     */
    private void resetOpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetOpButtonActionPerformed
        Object[] options = {"yes","no"};
        int response = JOptionPane.showOptionDialog(table, "Are you sure you want to reset all the variables", "Resetting", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, "");
        if(response == 0){
            manager.resetVariables();
            
        }
        buildTable();
    }//GEN-LAST:event_resetOpButtonActionPerformed

    private void storeInVariableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeInVariableButtonActionPerformed
       try {
           manager.processInput(">" + selectedVariable);
       } catch (NumberFormatException | NotEnoughOperatorsException | ArithmeticException | NoSuchElementException ex) {
           JOptionPane.showMessageDialog(table, ex.getMessage());
       }
    }//GEN-LAST:event_storeInVariableButtonActionPerformed

    private void loadFromVariableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFromVariableButtonActionPerformed
        try {
           manager.processInput("<" + selectedVariable);
       } catch (NumberFormatException | NotEnoughOperatorsException | ArithmeticException | NoSuchElementException ex) {
           JOptionPane.showMessageDialog(table, ex.getMessage());
       }
    }//GEN-LAST:event_loadFromVariableButtonActionPerformed

    private void sumToVariableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumToVariableButtonActionPerformed
        try {
           manager.processInput("+" + selectedVariable);
       } catch (NumberFormatException | NotEnoughOperatorsException | ArithmeticException | NoSuchElementException ex) {
           JOptionPane.showMessageDialog(table, ex.getMessage());
       }
    }//GEN-LAST:event_sumToVariableButtonActionPerformed

    private void substractToVariableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractToVariableButtonActionPerformed
        try {
           manager.processInput("-" + selectedVariable);
       } catch (NumberFormatException | NotEnoughOperatorsException | ArithmeticException | NoSuchElementException ex) {
           JOptionPane.showMessageDialog(table, ex.getMessage());
       }
    }//GEN-LAST:event_substractToVariableButtonActionPerformed


    //--------------------------------------------------------- Private Methods -----------------------------------------------------------------
    
    /**
     * This methods fill the table with the values of the Variables
     */
    private void buildTable(){
        model.setRowCount(0);
        Iterator<String> itr = manager.getVariables();
        while(itr.hasNext()){
            String[] row = itr.next().split(":");
            model.addRow(new Object[]{row[0],row[1],row[2]});  
            }
    }
    
    /**
     * This methods update the table when an operation on Variables occur
     * @param o
     * @param arg 
     */
    @Override
    public void update(Observable o, Object arg) {
        buildTable();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loadFromVariableButton;
    private javax.swing.JButton resetOpButton;
    private javax.swing.JButton restoreButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton storeInVariableButton;
    private javax.swing.JButton substractToVariableButton;
    private javax.swing.JButton sumToVariableButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    
}
